spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://localhost:3306/test1
      username: root   # 只读账户
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://localhost:3306/test2
      username: root   # 只读账户
      password: root
      driver-class-name: com.mysql.jdbc.Driver