package com.clk.datasource.bean;

import java.util.Date;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.user_id
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.user_name
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.gender
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.birthday
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.update_time
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.create_time
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.user_id
     *
     * @return the value of member.user_id
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.user_id
     *
     * @param userId the value for member.user_id
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.user_name
     *
     * @return the value of member.user_name
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.user_name
     *
     * @param userName the value for member.user_name
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.gender
     *
     * @return the value of member.gender
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.gender
     *
     * @param gender the value for member.gender
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.birthday
     *
     * @return the value of member.birthday
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.birthday
     *
     * @param birthday the value for member.birthday
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.update_time
     *
     * @return the value of member.update_time
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.update_time
     *
     * @param updateTime the value for member.update_time
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.create_time
     *
     * @return the value of member.create_time
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.create_time
     *
     * @param createTime the value for member.create_time
     *
     * @mbg.generated Thu Mar 21 10:59:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}